# Generated by Django 4.0.4 on 2022-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Contenido'),
        ),
    ]
