# Generated by Django 4.0.4 on 2022-06-20 23:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Contenido'),
        ),
    ]
