# Generated by Django 4.0.4 on 2022-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
    ]
