# Generated by Django 4.0.4 on 2022-06-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={},
        ),
    ]
